#! /bin/bash

GIT_DIR="/challenge/.remote"
GIT_FLAGS="--git-dir=${GIT_DIR}"

echo "Checking level..."

COMMIT=$(git ${GIT_FLAGS} rev-parse master)

echo "Inspecting commit ${COMMIT}"

## Check that the root tree has the proper hash
if git ${GIT_FLAGS} cat-file -p ${COMMIT} | grep "tree e58562979d51531c06ad23f3c196f34c94342ebc"; then
    echo "Passed!"
    exit 0
fi

echo "Not quite there, but keep trying!"
