#! /bin/bash

set -x

GIT_DIR="/challenge/.remote"
GIT_FLAGS="--git-dir=${GIT_DIR}"

echo "Checking level..."

COMMIT=$(git ${GIT_FLAGS} rev-parse master)

echo "Inspecting commit ${COMMIT}"

if git ${GIT_FLAGS} cat-file -p ${COMMIT} | grep "tree 2642f3c7e0342fc9b7270fe26cd38edbe1bc5c5a"; then
    echo "Passed!"
    exit 0
fi

echo "Not quite there"
